name: Desktop-release

on:
  push:
    branches:
      - desktop

jobs:
  release-mac:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install, lint and/or test
        run: |
          yarn
          cd src/desktop
          yarn

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          package_root: "./src/desktop/"
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          args: "--publish always"
          max_attempts: "5"
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

  release-win:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install, lint and/or test
        run: |
          yarn
          cd src/desktop
          yarn

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          package_root: "./src/desktop/"
          windows_certs: ${{ secrets.windows_certs }}
          windows_certs_password: ${{ secrets.windows_certs_password }}
          args: "--publish always"
          max_attempts: "5"
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

  release-unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install, lint and/or test
        run: |
          yarn
          cd src/desktop
          yarn

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          package_root: "./src/desktop/"
          args: "--publish always"
          max_attempts: "5"
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
